"""Add quantity and status to trip_items table

Revision ID: 115be744145d
Revises: 72e4c3d18a0f
Create Date: 2025-08-10 21:07:15.167023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115be744145d'
down_revision: Union[str, Sequence[str], None] = '72e4c3d18a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_items', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('trip_items', sa.Column('status', sa.Enum('UNPACKED', 'PACKED', 'TO_BUY', name='itemstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_items', 'status')
    op.drop_column('trip_items', 'quantity')
    # ### end Alembic commands ###
