"""setting entities name to be unique

Revision ID: bee86553ca1a
Revises: 8c8a963e4527
Create Date: 2025-08-06 20:58:23.220904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bee86553ca1a'
down_revision: Union[str, Sequence[str], None] = '8c8a963e4527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'items', ['name'])
    op.create_unique_constraint(None, 'bag', ['name'])
    op.create_unique_constraint(None, 'trips', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='unique')
    op.drop_constraint(None, 'bag', type_='unique')
    op.drop_constraint(None, 'items', type_='unique')
    # ### end Alembic commands ###
